### ISSUE TITLE
MX Version

### ISSUE THREAD

**Issue by michix** [tapioki/cephalopoda#7]
I really love the keyboard and the splay combined with the aggressive stagger. However, I'm really not a fan of chocs. Is there also an MX version available?

**Comment by michix** [comment]
Asked that question on Discord.

**Comment by hadaad** [comment]
> Asked that question on Discord.

Which discord server did you ask on? Did you get an answer? I'm also really interested in having a cherry version of this keyboard. I've built the choc version and I love it, but I think I like my cherry tactile switches more than the choc switches I'm using.

**Comment by michix** [comment]
I asked that in the Absolem Discord here (channel #tapi): https://discord.gg/DbCfZfZ
Indeed there is an unfinished MX version of the a.dux but no release so far since there are some unresolved issues yet. I'm also very keen on this version!
